name1 = input("Receiver:")
name2 = input("Sender:")
print("############################")
print(name1)
print()
print("Happy New Year to you.")
print()
print("           yours",name2)
print("############################")